apiVersion: v1
kind: Pod
metadata:
  namespace: default
  annotations:
    subject: this is a pod used for nginx app
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

